# Generated by Django 5.0.14 on 2026-05-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Característica')),
                ('icono', models.CharField(blank=True, default='bi-check-circle', help_text='Clase de Bootstrap Icons. Ej: bi-wifi, bi-tv, bi-droplet', max_length=50, verbose_name='Icono Bootstrap')),
            ],
            options={
                'verbose_name': 'Característica de habitación',
                'verbose_name_plural': 'Características de habitaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UbicacionHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la ubicación')),
                ('descripcion', models.TextField(blank=True, help_text='Opcional: detalle adicional sobre esta ubicación', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ubicación de habitación',
                'verbose_name_plural': 'Ubicaciones de habitaciones',
                'ordering': ['nombre'],
            },
        ),
    ]
