# Generated by Django 5.0.14 on 2026-05-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PisoSeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('PISO', 'Piso'), ('CHALET', 'Chalet'), ('BUNGALOW', 'Bungalow'), ('BLOQUE', 'Bloque'), ('ALA', 'Ala'), ('CABAÑA', 'Cabaña')], default='PISO', max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Piso / Sección',
                'verbose_name_plural': 'Pisos / Secciones',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
