# Generated by Django 5.0.14 on 2026-05-19 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default='#007bff', help_text='Color en formato hexadecimal. Ej: #FF0000 para rojo', max_length=7)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Tipo de Temporada',
                'verbose_name_plural': 'Tipos de Temporada',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('año', models.PositiveSmallIntegerField(help_text='Año al que pertenece esta temporada')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporadas', to='temporadas.tipotemporada')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['año', 'fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TarifaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('precio_por_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='hotel.tipohabitacion')),
                ('tipo_temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifas', to='temporadas.tipotemporada')),
            ],
            options={
                'verbose_name': 'Tarifa de Habitación',
                'verbose_name_plural': 'Tarifas de Habitaciones',
                'unique_together': {('tipo_habitacion', 'tipo_temporada')},
            },
        ),
    ]
