# Generated by Django 5.0.14 on 2026-05-19 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotel', '0002_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('aplicacion', models.CharField(choices=[('HOTEL', 'Hotel'), ('RESTAURANT', 'Restaurant'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='grupos/')),
            ],
            options={
                'verbose_name': 'Grupo de Producto',
                'verbose_name_plural': 'Grupos de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('aplicacion', models.CharField(choices=[('HOTEL', 'Hotel'), ('RESTAURANT', 'Restaurant'), ('AMBOS', 'Ambos')], default='AMBOS', max_length=15)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio_publico', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Público General')),
                ('precio_huesped', models.DecimalField(decimal_places=2, help_text='Precio especial para huéspedes del hotel', max_digits=10, verbose_name='Precio Huésped')),
                ('precio_personal', models.DecimalField(decimal_places=2, help_text='Precio para empleados', max_digits=10, verbose_name='Precio Personal')),
                ('disponible', models.BooleanField(default=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='restaurant.grupoproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['grupo', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('cantidad', models.PositiveSmallIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FACTURADO', 'Facturado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True)),
                ('registro_hospedaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='hotel.registrohospedaje')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.producto')),
            ],
            options={
                'verbose_name': 'Consumo a Habitación',
                'verbose_name_plural': 'Consumos a Habitaciones',
                'ordering': ['-fecha_consumo'],
            },
        ),
    ]
