# Generated by Django 5.0.14 on 2026-05-19 18:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDelDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha', models.DateField(unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio del menú completo')),
                ('disponible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Menú del Día',
                'verbose_name_plural': 'Menús del Día',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('fecha', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_hospedajes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_restaurant_publico', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_restaurant_habitaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_general', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('cerrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SOPA', 'Sopa'), ('PLATO', 'Plato Fuerte'), ('POSTRE', 'Postre'), ('BEBIDA', 'Bebida')], max_length=10)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.menudeldia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.producto')),
            ],
            options={
                'verbose_name': 'Ítem del Menú',
                'verbose_name_plural': 'Ítems del Menú',
                'unique_together': {('menu', 'categoria')},
            },
        ),
        migrations.AddField(
            model_name='menudeldia',
            name='productos',
            field=models.ManyToManyField(through='restaurant.MenuItem', to='restaurant.producto'),
        ),
    ]
