# Generated by Django 5.0.14 on 2026-05-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menudeldia_cierrecaja_menuitem_menudeldia_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudeldia',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='menudeldia',
            unique_together={('nombre', 'fecha')},
        ),
    ]
