# Generated by Django 5.0.14 on 2026-05-19 16:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('documento_identidad', models.CharField(help_text='RIF, Pasaporte, Cédula, DNI', max_length=50, unique=True, verbose_name='Documento de identidad')),
                ('nacionalidad', models.CharField(default='Venezolano', max_length=100, verbose_name='Nacionalidad')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono principal')),
                ('telefono_alternativo', models.CharField(blank=True, max_length=20, verbose_name='Teléfono alternativo')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
            ],
            options={
                'verbose_name': 'Huésped',
                'verbose_name_plural': 'Huéspedes',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('codigo', models.CharField(help_text='Ej: 101, 202A, PH-01', max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text="Ej: 'Suite Imperial', 'Doble 101'", max_length=100, verbose_name='Nombre descriptivo')),
                ('extension_telefono', models.CharField(blank=True, max_length=10, verbose_name='Extensión telefónica')),
                ('piso', models.PositiveSmallIntegerField(help_text='Para ordenamiento visual en el panel', verbose_name='Número de piso')),
                ('notas_internas', models.TextField(blank=True, help_text="Visible solo para empleados. Ej: 'Aire acondicionado ruidoso'", verbose_name='Notas internas')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='core.ubicacionhabitacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['piso', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='EstadoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('estado', models.CharField(choices=[('DISPONIBLE', '✅ Disponible'), ('OCUPADA', '🚫 Ocupada'), ('SUCIA', '🧹 En Limpieza'), ('MANTENIMIENTO', '🔧 Mantenimiento'), ('RESERVADA', '📅 Reservada')], max_length=20, verbose_name='Estado')),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Inicio del estado')),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Si está vacío, este es el estado actual', null=True, verbose_name='Fin del estado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del cambio de estado')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='hotel.habitacion', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Estado de habitación',
                'verbose_name_plural': 'Historial de estados',
                'ordering': ['-fecha_inicio'],
                'get_latest_by': 'fecha_inicio',
            },
        ),
        migrations.CreateModel(
            name='HabitacionFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('imagen', models.ImageField(upload_to='habitaciones/fotos/%Y/%m/', verbose_name='Imagen original')),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Número menor = aparece primero', verbose_name='Orden de visualización')),
                ('es_principal', models.BooleanField(default=False, help_text='Solo una foto por habitación debe ser principal', verbose_name='¿Foto principal?')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='hotel.habitacion', verbose_name='Habitación')),
            ],
            options={
                'verbose_name': 'Foto de habitación',
                'verbose_name_plural': 'Fotos de habitaciones',
                'ordering': ['habitacion', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHospedaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('fecha_checkin', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y hora de check-in')),
                ('fecha_checkout', models.DateTimeField(blank=True, help_text='Vacío = huésped aún en el hotel', null=True, verbose_name='Fecha y hora de check-out')),
                ('cantidad_personas', models.PositiveSmallIntegerField(help_text='Incluyendo al huésped principal', verbose_name='Cantidad de personas')),
                ('tarifa_aplicada', models.DecimalField(decimal_places=2, help_text='Precio acordado al momento del check-in', max_digits=10, verbose_name='Tarifa por noche')),
                ('notas', models.TextField(blank=True, verbose_name='Notas del hospedaje')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_hospedaje', to='hotel.habitacion', verbose_name='Habitación')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_hospedaje', to='hotel.huesped', verbose_name='Huésped principal')),
            ],
            options={
                'verbose_name': 'Registro de hospedaje',
                'verbose_name_plural': 'Registros de hospedaje',
                'ordering': ['-fecha_checkin'],
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Se establece automáticamente al crear el registro', verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Se actualiza automáticamente en cada save()', verbose_name='Última actualización')),
                ('activo', models.BooleanField(default=True, help_text='False = eliminación lógica (soft delete)', verbose_name='Activo')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Tipo de habitación')),
                ('capacidad_maxima', models.PositiveSmallIntegerField(help_text='Número máximo de huéspedes permitidos', verbose_name='Capacidad máxima de personas')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del tipo')),
                ('caracteristicas', models.ManyToManyField(blank=True, help_text='Amenities que incluye este tipo de habitación', to='core.caracteristicahabitacion', verbose_name='Características incluidas')),
            ],
            options={
                'verbose_name': 'Tipo de habitación',
                'verbose_name_plural': 'Tipos de habitaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='hotel.tipohabitacion', verbose_name='Tipo de habitación'),
        ),
    ]
