# Generated by Django 5.0.14 on 2026-05-19 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_reserva'),
        ('usuarios', '0002_cargo_tipocliente_turno_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='tipo_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huespedes', to='usuarios.tipocliente', verbose_name='Tipo de Cliente'),
        ),
    ]
