# Generated by Django 5.0.14 on 2026-05-19 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_huesped_tipo_cliente'),
        ('usuarios', '0003_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohospedaje',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hospedajes', to='usuarios.cliente', verbose_name='Facturar a'),
        ),
    ]
