# Generated by Django 5.0.14 on 2026-05-20 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pisoseccion'),
        ('hotel', '0004_registrohospedaje_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['piso_seccion__orden', 'codigo'], 'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='piso',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='piso_seccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='core.pisoseccion', verbose_name='Piso / Sección'),
        ),
    ]
